services:
  java-backend:
    image: java-backend # Utilise votre image existante
    container_name: java-backend-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Mappe le port 8080 de l'hôte au conteneur
    networks:
      - shared-network
    restart: unless-stopped

networks:
  shared-network:
    external: true